config/routes.rb
Rails.application.routes.draw do

  get '/join', to: 'join#index'
  post '/join/signup', to: 'join#signup'

  devise_for :users, controllers: {
    passwords: 'passwords',
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user do
    get '/password_reset', to: 'passwords#password_reset'
    get '/sign_up', to: 'registrations#sign_up'
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :users
  resources :families
  resources :profiles do
    get 'download_pdf', to: 'profile#download_pdf'
  end

  post 'change_family', to: 'profile#change_family'
  post 'add_family', to: 'profile#change_family'
  post 'change_basic_info', to: 'profile#change_basic_info'
  post 'change_education', to: 'profile#change_education'
  post 'add_educations', to: 'profile#change_education'
  post 'change_work_experience', to: 'profile#change_work_experience'
  post 'add_work_experience', to: 'profile#change_work_experience'
  post 'change_language', to: 'profile#change_language'
  post 'add_language', to: 'profile#change_language'
  post 'change_certification', to: 'profile#change_certification'
  post 'add_certification', to: 'profile#change_certification'

  resources :avatar, only: %i[update destroy]
  resources :profile_steps

  root 'join#index'
end

app/controllers/profile_steps_controller.rb
class ProfileStepsController < ApplicationController
  include Wicked::Wizard
  include AddFamily
  include WorkEducationExperience
  include WorkCertification
  include Translatable

  steps :personal_info, :family, :work_education_experience, :summary
  before_action :set_user, :set_profile

  def show
    @user.reload unless @user.profile.present?
    populate_available_options_for_data

    render_wizard
  end

  def update
    @certifications = certifications
    @degree_of_kinships = degree_of_kinships
    @form_of_educations = form_of_educations
    @degrees = degrees
    @language_levels = language_levels

    save_current_step
    personal_info_save || family_save || work_education_experience_save || summary_save
  end

  def finish_wizard_path
    send_resume_pdf

    reset_session
    root_path
    #render_wizard @user
  end

  def summary_save
    return false unless wizard_value(step) == :summary

    @profile.save
    render_wizard @user

    true
  end

  def personal_info_save
    return false unless wizard_value(step) == :personal_info

    @user.location = params[:user][:location]
    @user.personal_tax_number = params[:user][:personal_tax_number]
    @user.birthday = params[:user][:birthday]
    @user.save
    render_wizard @user

    true
  end

  def family_save
    return false unless wizard_value(step) == :family

    add_family

    render wizard_path(:family)

    true
  end

  def work_education_experience_save
    return false unless wizard_value(step) == :work_education_experience

    profile_education_save
    work_experience_save
    certification_save
    language_save

    render wizard_path(:work_education_experience)

    true
  end

  private

  def send_resume_pdf
    recipient = 'support@gmail.com'
    #byebug
    output = UserResume.new(@user).content
    user = @user.id
    ResumeMailer.send_resume(output, recipient, user).deliver
  end

  def set_user
    @user ||= current_user
  end

  def set_profile
    @profile = @user.profile || Profile.create(user_id: @user.id)
  end

  def save_current_step
    @profile.current_step = wizard_value(next_step)
    @profile.save
  end

  def certifications
    @certifications ||= Certification.pluck(:description, :id)
  end

  def degree_of_kinships
    @degree_of_kinships ||= DegreeOfKinship.pluck(translation_for(:description), :id)
  end

  def form_of_educations
    @form_of_educations ||= FormOfEducation.pluck(translation_for(:description), :id)
  end

  def degrees
    @degrees ||= Degree.pluck(translation_for(:description), :id)
  end

  def language_levels
    @language_levels ||= LanguageLevel.pluck(translation_for(:description), :id)
  end

  def populate_available_options_for_data
    certifications
    degree_of_kinships
    form_of_educations
    degrees
    language_levels
  end
end

app/helpers/profile_steps_helper.rb
module ProfileStepsHelper
end

app/views/profile_steps/_add_education.html.erb
<!--Add Education Modal-->
<div class="modal fade" id="addEducationModal" tabindex="-1" role="dialog" aria-labelledby="addEducationModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="modalLabel"><%= t('interface.steps.education.form.add_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_for :profile_education, url: wizard_path, method: :put do |f| %>
        <%= render partial: 'forms/form_educations', locals: {profile_education: nil, f: f,
                                                              modal_id: (@profile&.profile_educations&.size.to_i + 1)} %>

    <% end %>
    </div>
  </div>
</div>

app/views/profile_steps/_add_family.html.erb
<!--Add Family Modal-->
<div class="modal fade" id="addFamilyModal" tabindex="-1" role="dialog" aria-labelledby="addFamilyModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="modalLabel"><%= t('interface.steps.family.form.add_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_for :family, url: wizard_path, method: :put do |f| %>
        <%= render partial: 'forms/form_family', locals: { family: nil, f: f,
                                                           modal_id: (@profile.families.size + 1),
                                                           profile: @profile } %>
      <% end %>
    </div>
  </div>
</div>

app/views/profile_steps/_add_language.html.erb
<!--Add Family Modal-->
<div class="modal fade" id="addLanguageModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="modalLabel"><%= t('interface.steps.language.form.add_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_for :language, url: wizard_path, method: :put do |f| %>
        <%= render partial: 'forms/form_language', locals: { language: nil, f: f,
                                                           profile: @profile } %>
      <% end %>
    </div>
  </div>
</div>

app/views/profile_steps/_add_licences_or_certification.html.erb
<!--Add License or Certification Modal-->
<div class="modal fade" id="addLicenseCertificationModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="modalLabel"><%= t('interface.steps.certification.form.add_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_for :profile_certification, url: wizard_path, method: :put do |f| %>
        <%= render partial: 'forms/form_certifications', locals: {profile_certification: nil, f: f} %>
      <% end %>
    </div>
  </div>
</div>
<%= render partial: 'shared/certification_validations', locals: { profile: nil, profile_certification: nil } %>

<script>
  $('#selectCertification').on('click', () => {
    $('#customDescriptionCertificate').val('');
  })
</script>

app/views/profile_steps/_add_work_experience.html.erb
<!--Add Work Experience Modal-->
<div class="modal fade" id="addWorkExperienceModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="modalLabel"><%= t('interface.steps.work.form.add_title') %></h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <%= form_for :profile_experience, url: wizard_path, method: :put do |f| %>
        <%= render partial: 'forms/form_work_experience', locals: { profile_experience: nil, f: f,
                                                                     modal_id: (@profile.profile_experiences.size + 1),
                                                                     profile: @profile } %>
      <% end %>
    </div>
  </div>
</div>
<%= render partial: 'profile_steps/date_validation' %>

app/views/profile_steps/_date_validation.html.erb
<script>
    $(document).on('turbolinks:load', function () {
        $('.submit-work-education').on('click', (e) => {
            const currentModalId = $(e.target).data('id');
            const start_date = new Date($('#startYear-' + currentModalId).val(), ($('#startMonth-' + currentModalId).val() - 1));
            const end_date = new Date($('#endYear-' + currentModalId).val(), ($('#endMonth-' + currentModalId).val() - 1));
            const alertElement = document.getElementById('alertWarning-' + currentModalId);

            if (!$('#currentJob-' + currentModalId).prop('checked') && (start_date > end_date)) {
                alertElement.classList.remove('d-none');
                alertElement.classList.add('d-block');
                e.preventDefault();
                e.stopPropagation();
            }
        });
    })
</script>

app/views/profile_steps/_edit_education.html.erb
<!--Edit Education Modal-->
<div class="modal fade" id="editEducationModal-<%= profile_education.id %>" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="postJobStep1Label"><%= t('interface.steps.education.form.edit_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_for :profile_education, url: wizard_path, method: :put do |f| %>
        <%= render partial: 'forms/form_educations', locals: {profile_education: profile_education, f: f,
                                                              modal_id: profile_education.id} %>
      <% end %>
    </div>
  </div>
</div>
<script>
  <% if @profile.profile_educations.count > 1 %>
    $('.modal-footer').addClass('justify-content-between');
    $('.btn-outline-danger').removeClass('d-none');
  <% end %>
</script>

app/views/profile_steps/_edit_family.html.erb
<!--Edit Family Modal-->
<div class="modal fade" id="editFamilyModal-<%= family.id %>" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="postJobStep1Label"><%= t('interface.steps.family.form.edit_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <%= form_for :family, url: wizard_path, method: :put do |f| %>
        <%= render partial: 'forms/form_family', locals: { family: family, f: f,
                                                           modal_id: (@profile.families.size + 1),
                                                           profile: @profile } %>
      <% end %>
    </div>
  </div>
</div>

app/views/profile_steps/_edit_licences_or_certification.html.erb
<!--Edit License or Certification Modal-->
<div class="modal fade" id="editLicenseCertificationModall-<%= profile_certification.id %>" tabindex="-1" role="dialog" aria-labelledby="modelLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="postJobStep1Label"><%= t('interface.steps.certification.form.edit_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_for :profile_certification, url: wizard_path, method: :put do |f| %>
        <%= render partial: 'forms/form_certifications', locals: { profile: @profile,
                                                                    profile_certification: profile_certification, f: f} %>
      <% end %>
    </div>
  </div>
</div>
<%= render partial: 'shared/certification_validations', locals: { profile: @profile, profile_certification: profile_certification } %>

<script>
  $('#editSelectCertification-' + <%= profile_certification.id %>).on('click', () => {
    $('#customDescriptionCertificate-' + <%= profile_certification.id %>).val('');
  })
</script>

app/views/profile_steps/_edit_work_experience.html.erb
<div class="modal fade" id="editWorkExperienceModal-<%= profile_experience.id %>" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="modalLabel"><%= t('interface.steps.work.form.edit_title') %></h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <%= form_for :profile_experience, url: wizard_path, method: :put do |f| %>
        <%= render partial: 'forms/form_work_experience', locals: { profile_experience: profile_experience, f: f,
                                                                    modal_id: profile_experience.id,
                                                                    profile: @profile } %>
      <% end %>
    </div>
  </div>
</div>
<%= render partial: 'profile_steps/date_validation' %>

app/views/profile_steps/family.html.erb
<%= render 'nav_bar/profile_flow_nav_bar' %>
<div class="container pr-0 pl-0" style="max-width: 720px;"><%= render partial: 'shared/notice_and_alert' %></div>

<!--Progress Meter, Step 4-->
<div class="container mb-4">
  <div class="progress bg-white shadow-sm mx-auto" style="max-width: 700px;">
    <div class="progress-bar" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
  <div class="text-secondary font-weight-bold my-1 text-center">40%</div>
</div>

<div class="container">
  <div class="bp-card mb-5 mx-auto" style="max-width:800px">
    <div class="card-title text-center">
      <div class="h2">
        <div class="text-center">
          <h2><%= I18n.t('interface.steps.family.title') %></h2>
        </div>
        <div class="mb-4">
          <% if @profile.families.present? %>
            <% @profile.families.order(f_birthday: :asc).each do |family| %>
              <div class="d-flex mb-3">
                <div class="w-100">
                  <div class="row">
                    <div class="col mb-1 text text-wrap text-break"><%= family&.degree_of_kinship&.description %></div>
                  </div>
                  <div class="row bp-text-sm">
                    <div class="col-md text-wrap text-break"><%= family.full_name %>,<%= family.f_birthday %>
                      , <%= family.place_of_work %></div>
                  </div>
                </div>
                <%= render 'edit_family', { family: family } %>
                <button class="btn btn-link" type="button" data-toggle="modal" data-target="#editFamilyModal-<%= family.id %>">
                  <i class="fas fa-pencil-alt" style="font-size: 24px"></i></button>
              </div>
            <% end %>
          <% end %>
          <button class="btn btn-outline-primary" data-toggle="modal" data-target="#addFamilyModal">
            <i class="fas fa-plus mr-2"></i><%= t('button.add_new') %>
          </button>
        </div>
      </div>
      <div class="d-flex justify-content-between">
        <%= link_to I18n.t('button.back'), previous_wizard_path, class: "btn btn-link px-0" %>
        <%= link_to I18n.t('button.next'), next_wizard_path, class: "btn btn-primary", id: "NextBtn" %>
      </div>
    </div>
  </div>
</div>
</div>

<%= render 'add_family' %>

app/views/profile_steps/personal_info.html.erb
<%= render 'nav_bar/profile_flow_nav_bar' %>

<!--Progress Meter, Step 2-->
<div class="container mb-4">
  <div class="progress bg-white shadow-sm mx-auto" style="max-width: 700px;">
    <div class="progress-bar" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
  <div class="text-secondary font-weight-bold my-1 text-center">20%</div>
</div>

<div class="container">
  <div class="card mb-5 mx-auto" style="max-width:800px">
    <div class="card-title text-center">
      <div class="h2">
        <%= I18n.t('interface.steps.personal_info.title') %>
      </div>
    </div>
    <div class="card-body">
      <!--Content Card, Primary information-->
      <%= form_for @user, url: wizard_path, method: :put do |f| %>
        <div class="row">
          <div class="col-md mb-5 text-center avatar">
            <h2><%= I18n.t('interface.steps.personal_info.picture') %></h2>
            <p class="mb-4"><%= t('interface.steps.personal_info.placeholder.picture') %> <strong>(<%= t('interface.optional') %>)</strong></p>
            <% if @profile.avatar.attached? %>
              <div class="text-light mb-3 avatar-image" style="font-size: 170px;line-height: 0;">
                <%= image_tag @profile.avatar, class: 'rounded-circle' %>
              </div>
              <div class="custom-file">
                <%= f.file_field :profile_avatar, multiple: false, name: 'avatar', class: "d-none", id: "uploadProfilePic" %>
                <label class="btn btn-outline-primary mb-0" for="uploadProfilePic">
                  <%= I18n.t('button.upload_photo') %>
                </label>
                <button type="button" class="delete-avatar d-none" id="deleteProfilePic"></button>
                <label class="btn btn-outline-danger mb-0 ml-2" for="deleteProfilePic">
                  <%= I18n.t('button.delete') %>
                </label>
              </div>
            <% else %>
              <div class="text-light mb-3" style="font-size: 170px;line-height: 0;"><i class="fas fa-user-circle"></i></div>
              <div class="custom-file">
                <%= f.file_field :profile_avatar, multiple: false, name: 'avatar', class: "d-none", id: "uploadProfilePic" %>
                <label class="btn btn-outline-primary" for="uploadProfilePic">
                  <%= I18n.t('button.upload_photo') %>
                </label>
              </div>
            <% end %>
            <div class="error-avatar text-danger mt-1"></div>
          </div>
        </div>

        <div class="row">
          <div class="col-md text-center mb-5">
            <hr class="d-md-none mt-0">
            <div class="form-group text-left">
              <label for="freelancerLocationInput" class="h5"><%= t('interface.steps.personal_info.location') %></label>
              <%= f.text_field :location, class: "form-control", id: "freelancerLocationInput", placeholder: t('interface.steps.personal_info.placeholder.location'), required: true %>
            </div>
            <div class="error-location text-danger mb-2"></div>
          </div>
          <div class="col">
            <%= f.label I18n.t('interface.steps.personal_info.tax'), class: 'form-label' %>
            <%= f.text_field :personal_tax_number, class: 'form-control' %>
          </div>
          <div class="col-md text-wrap text-break">
            <%= f.label I18n.t('interface.steps.personal_info.birthday'), class: 'form-label' %>
            <%= f.date_field :birthday, class: 'form-control' %>
          </div>
        </div>

        <div class="justify-content-right">
          <%= f.submit I18n.t('button.next'), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $('#addAdditionalInfo').on ('click', function (e) {
    $('#additionalInformation').toggle('collapse')
  })

    $('.avatar').on('change', '#uploadProfilePic', function (e) {
        var file = e.target.files[0];
        var formData = new FormData();
        formData.append('avatar', file);
        $.ajax({
            url: '/avatar/update',
            method: 'PUT',
            contentType: false,
            processData: false,
            dataType: 'json',
            data: formData,
            success: function() {
                $('.avatar').load(' .avatar');
            }
        });
    });

    $('.avatar').on('click', '.delete-avatar', function (e) {
        $.ajax({
            url: '/avatar/destroy',
            method: 'DELETE',
            success: function() {
                $('.avatar').load(' .avatar');
            }
        })
    });


</script>

app/views/profile_steps/summary.html.erb
<%= render partial: 'navigation', locals: { section: 'jobs' } %>

<div class="container mb-5">
  <%= render partial: 'shared/notice_and_alert' %>
  <div class="mt-4">
    <div class="h1">
      <%= t('interface.steps.summary.title') %>
    </div>
  </div>
  <div class="container bp-card">
    <%= render partial: 'shared/summary' %>
    <hr>
    <div class="mt-3">
      <h4><%= t('user.email') %></h4>
      <p><%= @profile.user.email %></p>
    </div>
    <div class="mt-4">
      <div class="d-flex justify-content-between">
        <%= link_to 'Download', profile_download_pdf_path(@profile), class: "btn btn-primary", id: "NextBtn" %>
        <%= form_for @profile, url: wizard_path, method: :put do |f| %>
          <%= f.submit t('button.submit'), class: 'btn btn-primary d-none d-sm-block' %>
          <%= f.submit 'Submit', class: 'btn btn-primary d-sm-none' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profile_steps/work_education_experience.html.erb
<%= render '/nav_bar/profile_flow_nav_bar' %>
<div class="container pr-0 pl-0" style="max-width: 720px;"><%= render partial: 'shared/notice_and_alert' %></div>

<!--Progress Meter, Step 4-->
<div class="container mb-4">
  <div class="progress bg-white shadow-sm mx-auto" style="max-width: 700px;">
    <div class="progress-bar" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
  <div class="text-secondary font-weight-bold my-1 text-center">60%</div>
</div>

<!--Content Card, Step 4-->
<div class="container">
  <div class="bp-card mb-5 mx-auto" style="max-width: 700px;">
    <div class="text-center">
      <h2><%= t('interface.steps.work_education.title') %></h2>
      <p class="mb-4"><%= t('interface.steps.work_education.placeholder') %></p>
    </div>

    <div class="mb-4">
      <div class="h5">
        <%= t('interface.steps.work_education.child_title.work') %>
      </div>
      <% if @profile.profile_experiences.present? %>
        <% @profile.profile_experiences.order(current_job: :desc, end_date: :desc).each do |work_exp| %>
          <div class="d-flex align-items-center justify-content-between mb-3">
            <div class="w-100">
              <div class="row">
                <div class="col mb-1 text text-wrap text-break"><%= work_exp.job_title %></div>
              </div>
              <div class="row bp-text-sm">
                <div class="col-md text-wrap text-break"><%= work_exp.company %>, <%= work_exp.location %></div>
                <div class="col-md">
                  <%= l(work_exp.start_date, format: "%b %Y") %>-<%= work_exp.current_job.present? ? "Present" : l(work_exp.end_date, format: "%b %Y") %>
                </div>
              </div>
            </div>
            <%= render 'edit_work_experience', { profile_experience: work_exp, profile: @profile } %>
            <button class="btn btn-link" type="button" data-toggle="modal" data-target="#editWorkExperienceModal-<%= work_exp.id %>"><i class="fas fa-pencil-alt" style="font-size: 24px"></i></button>
          </div>
        <% end %>
      <% end %>
      <button class="btn btn-outline-primary" data-toggle="modal" data-target="#addWorkExperienceModal"><i class="fas fa-plus mr-2"></i><%= t('button.add_new') %></button>
    </div>

    <div class="mb-4">
      <div class="h5">
        <%= t('interface.steps.work_education.child_title.education') %>
      </div>
      <% if @profile.profile_educations.present? %>
        <% @profile.profile_educations.order(currently_studying: :desc, graduation_year: :desc).each do |education_exp| %>
          <div class="d-flex align-items-center justify-content-between mb-3">
            <div class="w-100">
              <div class="row">
                <div class="col mb-1 text text-wrap text-break"><%= education_exp.institution %></div>
              </div>
              <div class="row bp-text-sm">
                <div class="col-md text-wrap text-break">
                  <%= education_exp&.degree&.description %>,
                  <%= education_exp&.course_of_study %>,
                  <%= education_exp&.form_of_education&.description %></div>
                <div class="col-md"><%= education_exp.currently_studying.present? ? t('interface.steps.education.form.currently_studying') : education_exp.graduation_year %></div>
              </div>
            </div>
            <%= render 'edit_education', profile_education: education_exp %>
            <button class="btn btn-link" type="button" data-toggle="modal" data-target="#editEducationModal-<%= education_exp.id %>"><i class="fas fa-pencil-alt" style="font-size: 24px"></i></button>
          </div>
        <% end %>
      <% end %>
      <button class="btn btn-outline-primary" data-toggle="modal" data-target="#addEducationModal"><i class="fas fa-plus mr-2"></i><%= t('button.add_new') %></button>
    </div>

    <div class="mb-5">
      <div class="h5">
        <%= t('interface.steps.work_education.child_title.certification') %>
      </div>
      <% if @profile.profile_certifications.present? %>
        <% @profile.profile_certifications.order(earned: :desc).each do |certification| %>
          <div class="d-flex align-items-center justify-content-between mb-3">
            <div class="w-100">
              <div class="row">
                <div class="col-md text text-wrap text-break"><%= certification&.description %></div>
                <div class="col-md"> <%= t('interface.steps.work_education.earned') %> <%= l(certification&.earned, format: "%b %Y") %></div>
              </div>
            </div>
            <%= render 'edit_licences_or_certification', profile_certification: certification %>
            <button class="btn btn-link" type="button" data-toggle="modal" data-target="#editLicenseCertificationModall-<%= certification.id %>"><i class="fas fa-pencil-alt" style="font-size: 24px"></i></button>
          </div>
        <% end %>
      <% end %>
      <button class="btn btn-outline-primary" data-toggle="modal" data-target="#addLicenseCertificationModal"><i class="fas fa-plus mr-2"></i><%= t('button.add_new') %></button>
    </div>

    <div class="mb-5">
      <div class="h5">
        <%= t('interface.steps.work_education.child_title.language') %>
      </div>
    <% if @profile.languages.present? %>
      <% @profile.languages.each do |lang| %>
        <div class="d-flex align-items-center justify-content-between mb-3">
          <div class="w-100">
            <div class="row">
              <div class="col mb-1 text text-wrap text-break"><%= lang&.lang_know %> - <%= lang&.language_level&.description %></div>
            </div>
          </div>
          <%= render 'edit_language', language: lang %>
          <button class="btn btn-link" type="button" data-toggle="modal" data-target="#editLanguageModal-<%= lang.id %>"><i class="fas fa-pencil-alt" style="font-size: 24px"></i></button>
        </div>
      <% end %>
    <% end %>
    <button class="btn btn-outline-primary" data-toggle="modal" data-target="#addLanguageModal"><i class="fas fa-plus mr-2"></i><%= t('button.add_new') %></button>
  </div>

    <div class="d-flex justify-content-between">
      <%= link_to I18n.t('button.back'), previous_wizard_path, class: "btn btn-link px-0" %>
      <%= link_to I18n.t('button.next'), next_wizard_path, class: "btn btn-primary", id: "NextBtn" %>
    </div>
  </div>
</div>

<script>
    $('#NextBtn').click(function(event){
      if (<%= @profile.profile_educations.blank? || @profile.profile_experiences.blank? %>) {
        event.preventDefault();
      }
    });
</script>

<%= render 'add_work_experience', { timestamp: Time.current.to_i, profile: @profile } %>
<%= render 'add_education' %>
<%= render 'add_licences_or_certification', certification: @certification %>
<%= render 'add_language' %>