config/routes.rb
Rails.application.routes.draw do

  get '/join', to: 'join#index'
  post '/join/signup', to: 'join#signup'

  devise_for :users, controllers: {
    passwords: 'passwords',
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user do
    get '/password_reset', to: 'passwords#password_reset'
    get '/sign_up', to: 'registrations#sign_up'
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :users
  resources :families
  resources :profiles do
    get 'download_pdf', to: 'profile#download_pdf'
  end

  post 'change_family', to: 'profile#change_family'
  post 'add_family', to: 'profile#change_family'
  post 'change_basic_info', to: 'profile#change_basic_info'
  post 'change_education', to: 'profile#change_education'
  post 'add_educations', to: 'profile#change_education'
  post 'change_work_experience', to: 'profile#change_work_experience'
  post 'add_work_experience', to: 'profile#change_work_experience'
  post 'change_language', to: 'profile#change_language'
  post 'add_language', to: 'profile#change_language'
  post 'change_certification', to: 'profile#change_certification'
  post 'add_certification', to: 'profile#change_certification'

  resources :avatar, only: %i[update destroy]
  resources :profile_steps

  root 'join#index'
end

app/views/shared/_about_short.html.erb
<div class="d-flex">
  <div class="d-flex flex-sm-row flex-column">
    <% if profile.avatar.attached? %>
      <div class="text-light avatar-image" style="line-height: 0;">
        <%= image_tag profile.avatar, class: 'rounded-circle', width: '80px', height: '80px' %>
      </div>
    <% else %>
      <div class="text-light avatar-image" style="font-size: 80px; line-height: 0;">
        <i class="fas fa-user-circle"></i>
      </div>
    <% end %>
    <div class="ml-sm-3 mt-1 align-self-sm-center mt-sm-0">
      <h2 class="mb-1"><%= profile.full_name %></h2>
      <div class="bp-text-sm">
        <%= profile.professional_title %><br>
      </div>
    </div>
  </div>
    <div class="d-flex-col ml-auto">
      <button class="btn btn-link shadow-none p-0 align-self-start ml-auto" type="button"  data-bs-toggle="modal" data-bs-target="#editProfileModal-<%= profile.id %>"><i class="fas fa-edit text-primary"></i></button>
    </div>
    <%= render 'shared/edit_basic_info', profile: profile, redirect_reference: '' %>
</div>

app/views/shared/_add_certifications.html.erb
<!--Add License or Certification Modal-->
<div class="modal fade" id="addLicenseCertificationModal" tabindex="-1" role="dialog" aria-labelledby="modelLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="postJobStep1Label"><%= t('interface.steps.certification.form.add_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_for :profile_certification, url: add_certification_path do |f| %>
        <%= render partial: 'forms/form_certifications', locals: {profile_certification: nil, f: f} %>
      <% end %>
    </div>
  </div>
</div>

<script>
    $('#selectCertification').on('click', () => {
        $('#customDescriptionCertificate').val('');
    })
</script>

app/views/shared/_add_educations.html.erb
<!--Add Education Modal-->
<div class="modal fade" id="addEducationModal" tabindex="-1" role="dialog" aria-labelledby="modelLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="postJobStep1Label"><%= t('interface.steps.education.form.add_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_for :profile_education, url: change_education_path do |f| %>
        <%= render partial: 'forms/form_educations', locals: {profile_education: nil, f: f,
                                                               modal_id: (@profile&.profile_educations&.size.to_i + 1)} %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_add_family.html.erb
<!--Add Family Modal-->
<div class="modal fade" id="addFamilyModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="postJobStep1Label"><%= t('interface.steps.family.form.add_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_for :family, url: change_family_path do |f| %>
        <%= render partial: 'forms/form_family', locals: { family: nil, f: f } %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_add_language.html.erb
<!--Add Language Modal-->
<div class="modal fade" id="addLanguageModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="postJobStep1Label"><%= t('interface.steps.language.form.add_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_for :language, url: change_language_path do |f| %>
        <%= render partial: 'forms/form_language', locals: { language: nil, f: f,
                                                             modal_id: (@profile.languages.size + 1),
                                                             profile: @profile } %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_certification_validations.html.erb
<script>
  <% if profile && profile&.profile_certifications&.count > 1 %>
    $('.modal-footer').addClass('justify-content-between');
    $('.btn-outline-danger').removeClass('d-none');
  <% end %>

  $('.submitCertification<%= profile_certification&.id %>').on('click', (e) => {
    debugger
    if (($("#descriptionCertification-<%= profile_certification&.id %>").val() == '' && !$('#editCertificationCustom-<%= profile_certification&.id %>').is(':checked')) || ($('#editCertificationCustom-<%= profile_certification&.id %>').is(':checked') && $("#customDescriptionCertificate-<%= profile_certification&.id %>").val() == '')) {
      e.preventDefault();
      $('.error_description').text('Please make a selection');
      $(".descriptionCertification-<%= profile_certification&.id %>").addClass('error');
      $('.error_custom').text('Enter your custom license');
      $("#customDescriptionCertificate-<%= profile_certification&.id %>").addClass('error');
      setTimeout(() => {
        $('.error_description').text('');
        $(".descriptionCertification-<%= profile_certification&.id %>").removeClass('error');
        $('.error_custom').text('');
        $("#customDescriptionCertificate-<%= profile_certification&.id %>").removeClass('error');
      }, 3000);
    }
    if ($("#earnedMonth-<%= profile_certification&.id %>").prop("selectedIndex") === 0) {
      e.preventDefault();
      $('.error_month').text('Please make a selection');
      $(".earnedMonth-<%= profile_certification&.id %>").addClass('error');
      setTimeout(() => {
        $('.error_month').text('');
        $(".earnedMonth-<%= profile_certification&.id %>").removeClass('error');
      }, 3000);
    }
    if ($("#earnedYear-<%= profile_certification&.id %>").prop("selectedIndex") === 0) {
      e.preventDefault();
      $('.error_year').text('Please make a selection');
      $(".earnedYear-<%= profile_certification&.id %>").addClass('error');
      setTimeout(() => {
        $('.error_year').text('');
        $(".earnedYear-<%= profile_certification&.id %>").removeClass('error');
      }, 3000);
    }
  })
</script>

app/views/shared/_edit_basic_info.html.erb
<!--Edit Profile Modal-->
<style>
  .highlight {
    border: 2px solid red;
    border-radius: 5px;
  }
</style>

<div class="modal fade" id="editProfileModal-<%= profile.id %>" tabindex="-1" role="dialog" aria-labelledby="editProfileModal" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1><%= t('interface.steps.summary.form.title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body pt-0">
        <div class="alert_from_js d-none">
          <div class="alert alert-warning">
            <span></span>
          </div>
        </div>
        <%= form_for :profile, url: change_basic_info_path do |f| %>

          <div class="mb-3 avatar">
            <% if profile.avatar.attached? %>
              <div class="d-flex flex-column flex-sm-row align-items-center">
                <div class="mr-sm-2 mb-2 mb-sm-0">
                  <%= image_tag profile.avatar.variant(resize: "80x80!").processed, class: 'rounded-circle' %>
                </div>
                
                <div id='avatarButtons'>
                  <div class="custom-file">
                    <%= f.file_field :profile_avatar,
                                     multiple: false,
                                     name: 'avatar',
                                     class: "d-none",
                                     id: "uploadProfilePic" %>
                    <label class="btn btn-outline-primary m-0 mb-2 mb-sm-0" for="uploadProfilePic">
                      Upload photo
                    </label>
                    <button type="button" class="delete-avatar d-none" id="deleteProfilePic"></button>
                    <label class="btn btn-outline-danger mb-0 ml-2 mb-2 mb-sm-0" for="deleteProfilePic">
                      <%= t('button.delete') %>
                    </label>
                  </div>
                </div>
              </div>
            <% else %>
              <div class="d-flex flex-column flex-sm-row align-items-center">
                <div class="text-light mr-sm-2 mb-2 mb-sm-0" style="font-size: 80px;line-height: 0;">
                  <i class="fas fa-user-circle"></i>
                </div>
                
                <div id="uploadButton">
                  <div class="custom-file">
                    <%= f.file_field :profile_avatar,
                                     multiple: false,
                                     name: 'avatar',
                                     class: "d-none",
                                     id: "uploadProfilePic" %>
                    <label class="btn btn-outline-primary mt-sm-0" for="uploadProfilePic">
                      <%= t('button.upload_photo') %>
                    </label>
                    
                  </div>
                </div>
                
              </div>
            <% end %>
            <div class="error-avatar text-danger mt-1"></div>
          </div>

          <div class="row">
            <div class="col-lg">
              <div class="form-group mb-3 wrapper">
                <label for="professionalTitleInput" class="h5"><%= t('user.first_name') %></label>
                <%= f.text_field :first_name, class: "form-control custom-validate", id: "firstNameInput", required: true %>
              </div>
            </div>
            <div class="col-lg">
              <div class="form-group mb-3 wrapper">
                <label for="professionalTitleInput" class="h5"><%= t('user.second_name') %></label>
                <%= f.text_field :second_name, class: "form-control custom-validate", id: "firstNameInput", required: true %>
              </div>
            </div>
            <div class="col-lg">
              <div class="form-group mb-3 wrapper">
                <label for="professionalTitleInput" class="h5"><%= t('user.last_name') %></label>
                <%= f.text_field :last_name, class: "form-control custom-validate", id: "lastNameInput", required: true %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg">
              <div class="form-group mb-3 wrapper">
                <label for="phoneNumberInput" class="h5"><%= t('interface.steps.summary.form.phone') %></label>
                <%= f.text_field :phone_number, class: "form-control custom-validate", id: "phoneNumberInput", required: true %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg">
              <div class="form-group mb-3 wrapper">
                <label for="personalTaxNumberInput" class="h5"><%= t('interface.steps.summary.form.tax') %></label>
                <%= f.text_field :personal_tax_number, class: "form-control custom-validate", id: "personalTaxNumberInput", required: true %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg">
              <div class="form-group mb-3 wrapper">
                <label for="professionalTitleInput" class="h5"><%= t('interface.steps.summary.form.professional_title') %></label>
                <%= f.text_field :professional_title, class: "form-control custom-validate", id: "professionalTitleInput", placeholder: t('interface.steps.summary.placeholder.profession'), required: true %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg">
              <div class="form-group text-left wrapper">
                <label for="freelancerLocationInput" class="h5"><%= t('interface.steps.summary.form.location') %></label>
                <%= f.text_field :location,
                                 class: "form-control custom-validate",
                                 id: "freelancerLocationInput",
                                 placeholder: "City, State abbreviation",
                                 required: true %>
              </div>
              <div class="error-location text-danger mb-2"></div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg">
              <div class="form-group mb-3 wrapper">
                <label for="professionalSummaryTextarea" class="h5"><%= t('interface.steps.summary.form.professional_summary') %></label>
                <%= f.text_area :professional_summary, class: "form-control custom-validate", id: "professionalSummaryTextarea", placeholder: t('interface.steps.summary.placeholder.describe'), rows: "4", maxlength: "1000", required: true %>
              </div>
            </div>
          </div>

          <div class="d-flex pt-3 justify-content-end">
            <button type="button" class="btn btn-link px-0 invisible"></button>
            <%= f.submit I18n.t('button.save_changes'), id: 'submitWithLocationCheck', class: 'btn btn-primary save-changes-submit' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/update_avatar', url: avatar_path %>


<script>
  $(document).on('turbolinks:load', function (e) {

    $('.select2').select2({
      placeholder: 'Select all that apply',
      allowClear: true
    });

    $('.custom-validate').each(function() {
      if (!$.trim($(this).val()).length) $(this).parents('.wrapper').addClass( "highlight" );
    });

    const $textarea = $('textarea');
    if (!$.trim($textarea.val())) {
      $textarea.parents('.wrapper').addClass("highlight");
    }

    $('.custom-validate').on('input change', function(e) {
      const $targetElement = $(e.target);
      if (!$.trim($targetElement.val())) {
        $(this).parents('.wrapper').addClass("highlight");
      } else {
        $targetElement.parents('.wrapper').removeClass("highlight");
      }
    });

    $('.save-changes-submit').on('click', function (e) {
      if ($('.highlight').length) {
        e.preventDefault();
      }
    })
  })
</script>

app/views/shared/_edit_certifications.html.erb
<div class="modal fade" id="editLicenseCertificationModal-<%= profile_certification.id %>" tabindex="-1" role="dialog" aria-labelledby="modelLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="postJobStep1Label"><%= t('interface.steps.certification.form.edit_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_for :profile_certification, url: change_certification_path do |f| %>
        <%= render partial: 'shared/form_certifications', locals: { profile_certification: profile_certification, f: f } %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_edit_educations.html.erb
<!--Edit Education Modal-->
<div class="modal fade" id="editEducationModal-<%= profile_education.id %>" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="postJobStep1Label"><%= t('interface.steps.education.form.edit_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_for :profile_education, url: change_education_path do |f| %>
        <%= render partial: 'forms/form_educations', locals: {profile_education: profile_education, f: f,
                                                              modal_id: profile_education.id} %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_edit_family.html.erb
<!--Edit Family Modal-->
<div class="modal fade" id="editFamilyModal-<%= family.id %>" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="postJobStep1Label"><%= t('interface.steps.family.form.edit_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_for :family, url: change_family_path do |f| %>
        <%= render partial: 'forms/form_family', locals: {family: family, f: f,
                                                          modal_id: family.id} %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_edit_language.html.erb
<!--Edit Language Modal-->
<div class="modal fade" id="editLanguageModal-<%= language.id %>" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="postJobStep1Label"><%= t('interface.steps.language.form.edit_title') %></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <%= form_for :language, url: change_language_path do |f| %>
        <%= render partial: 'forms/form_language', locals: { language: language, f: f } %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_hide_success_notice.html.erb
<script>
  $(document).ready(() => {
    setTimeout(() => {
      $('.alert-success').removeClass('d-block').addClass('d-none');
    }, 3000);
  });
</script>

app/views/shared/_notice_and_alert.html.erb
<div class="container mb-3">
  <% if flash[:notice].present? || flash[:alert].present? %>
    <div class="alert alert-<%= flash[:alert].present? ? 'warning' : 'success' %> alert-dismissible fade show">
      <button type="button" class="close" data-dismiss="alert" style="font-size:1.5rem;">&times;</button>
      <%= flash[:alert].present? ?  flash[:alert].html_safe : flash[:notice].html_safe %>
    </div>
  <% elsif flash[:warning].present? %>
    <div class="alert alert-attention alert-dismissible fade show"><i class="fas fa-exclamation-circle alert-attention-icon"></i>
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:warning].html_safe %>
    </div>
  <% end %>
</div>
<style>
  .alert-attention {
      background-color: #fff3cd;
      opacity: 75%;
  }
  .alert-attention-icon {
    color: #A7AA2B;
  }
</style>
<%= render 'shared/hide_success_notice' %>

app/views/shared/_update_avatar.html.erb
<script>
  $(document).on('turbolinks:load', function (e) {
    $('.avatar').off('change').on('change', '#uploadProfilePic', (e) => {
      const file = e.target.files[0];
      const maxFileSize = 2097152;
      if (!file) { return }
      if (file.size && file.size > maxFileSize && correct_type(file)) {
        $('.error-avatar').text('Please upload only a jpg, png or gif image. Uploaded files must not exceed 2MB');
        setTimeout(() => {
          $('.error-avatar').text('');
        }, 3000);
      } else if (correct_type(file)) {
        $('.error-avatar').text('Please upload only a jpg, png or gif image');
        setTimeout(() => {
          $('.error-avatar').text('');
        }, 3000);
      } else if (file.size && file.size > maxFileSize) {
        $('.error-avatar').text('Uploaded files must not exceed 2MB');
        setTimeout(() => {
          $('.error-avatar').text('');
        }, 3000);
      } else {
        const formData = new FormData();
        formData.append('avatar', file);
        $.ajax({
          url: '<%= url %>',
          method: 'PUT',
          contentType: false,
          processData: false,
          dataType: 'json',
          data: formData,
          success: function (data) {
            $('.avatar').load(' .avatar');
            const $container = $('.alert_from_js');
            if (data['message']) {
              $container.removeClass('d-none');
              $container.find('span').html(`${data['message']}`)
            } else {
              $container.find('span').html('');
              $container.addClass('d-none');
            }
          },
          error: () => {
            const message = 'This file can not be attached';
            Swal.fire({
              title: '<h5>Oops!</h5>',
              text: message
            });
          }
        });
      }
    });

    $('.avatar').off('click').on('click', '.delete-avatar', () => {
      $.ajax({
        url: '<%= url %>',
        method: 'DELETE',
        success: () => {
          $('.avatar').load(' .avatar');
        }
      })
    });

    const correct_type = (file) => {
      return file.type != 'image/jpeg' && file.type != 'image/jpg' && file.type != 'image/png' && file.type != 'image/gif'
    }
  })
</script>