config/routes.rb
Rails.application.routes.draw do

  get '/join', to: 'join#index'
  post '/join/signup', to: 'join#signup'

  devise_for :users, controllers: {
    passwords: 'passwords',
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user do
    get '/password_reset', to: 'passwords#password_reset'
    get '/sign_up', to: 'registrations#sign_up'
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :users
  resources :families
  resources :profiles do
    get 'download_pdf', to: 'profile#download_pdf'
  end

  post 'change_family', to: 'profile#change_family'
  post 'add_family', to: 'profile#change_family'
  post 'change_basic_info', to: 'profile#change_basic_info'
  post 'change_education', to: 'profile#change_education'
  post 'add_educations', to: 'profile#change_education'
  post 'change_work_experience', to: 'profile#change_work_experience'
  post 'add_work_experience', to: 'profile#change_work_experience'
  post 'change_language', to: 'profile#change_language'
  post 'add_language', to: 'profile#change_language'
  post 'change_certification', to: 'profile#change_certification'
  post 'add_certification', to: 'profile#change_certification'

  resources :avatar, only: %i[update destroy]
  resources :profile_steps

  root 'join#index'
end

app/controllers/join_controller.rb
# frozen_string_literal: true

class JoinController < ApplicationController
  before_action :check_signed_in
  before_action :check_blank_email, :check_existing_email, :check_valid_email, only: [:signup]

  def index
    @email = params[:email]
  end

  def signup
    session[:email] = user_email

    redirect_to new_user_registration_path
  end

  private

  def check_blank_email
    return unless user_email.blank?

    flash[:notice] = I18n.t 'devise.registrations.missing_email'
    redirect_to join_path
  end

  def check_existing_email
    return unless User.find_by(email: user_email).present?

    flash[:notice] = I18n.t('devise.registrations.already_exists',
                            email: user_email,
                            path: new_user_session_path(email: user_email))

    redirect_to join_path
  end

  def check_valid_email
    return if user_email.match?(Devise.email_regexp)

    flash[:notice] = I18n.t('devise.registrations.invalid_email', email: user_email)

    redirect_to join_path
  end

  def user_email
    params[:user][:email]
  end

  def check_signed_in
    redirect_to current_signup_step_url if user_signed_in?
  end
end

app/helpers/join_helper.rb
module JoinHelper
end

app/views/join/index.html.erb
<%= render 'nav_bar/link_to_login' %>

<div class="log-in-container p-3 p-sm-0">
  <div class="bp-card m-auto text-center" style="max-width:500px">
    <div class="h2 mb-3"><%= I18n.t('interface.hello') %></div>
    <div>
      <%= form_for(:user, url: join_signup_path) do |f| %>
        <%= render 'devise/shared/error_messages' %>
        <div class="field mb-3 text-left">
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control', placeholder: I18n.t('interface.placeholder.email'), id: "user_email"%>
        </div>

        <div class="actions">
          <%= f.submit I18n.t('interface.registration.sign_up_with_email'), class: "btn btn-primary btn-block" %>
        </div>
      <% end %>

      <div class="bp-or-border my-3"><span><%= t('interface.registration.or') %></span></div>

      <%= google_sign_in_button(image_pack_tag('media/images/icons8-google-48.png', size: '24x24', class: 'mr-2') + I18n.t('interface.registration.sign_up_with_gemail'), proceed_to: user_google_omniauth_callback_path(src: 'registrations#new'), class: "btn btn-outline-primary btn-block d-flex justify-content-center mb-3") %>

    </div>
    <div class="text-muted">
      <%= I18n.t('interface.help')%> <%= mail_to('support@google.com') %>
    </div>
  </div>
</div>

<% if @email %>
  <script>
      $(function() {
          $('#user_email').val('<%= @email %>');
      });
  </script>
<% end %>